### ISSUE TITLE
can not find cacheflush

### ISSUE THREAD

**Issue by Jarlene** [ele7enxxh/Android-Inline-Hook#1]
get the error: 'cacheflush' was not declared in this scope' when i build it something is missing?

**Comment by ele7enxxh** [comment]
What version of the NDK you are using?

**Comment by Jarlene** [comment]
android-ndk-r10b

**Comment by Jarlene** [comment]
the method cacheflush was used in doInlineHook method.so can not find it,when i build it

**Comment by ele7enxxh** [comment]
In some versions of the Android platform, there is no 'cacheflush' defined in the 'unistd.h'.You can add APP_PLATFORM in Applicaion.mk.

**Comment by Jarlene** [comment]
3q,i find it~

**Comment by Jarlene** [comment]
你尝试过在ｒｏｏｔ手机执行inline　ｈｏｏｋ吗？我这里好像会有问题，ａｎｒ

**Comment by ele7enxxh** [comment]
什么问题？
