### ISSUE TITLE
直接使用本进程PTRACE_ATTACH线程，会出现operation not permitted，即使赋予root权限也是同样的错误，具体原因不得而知

### ISSUE THREAD

**Issue by difcareer** [ele7enxxh/Android-Inline-Hook#10]
博客没有评论功能，特到回复一下。

根据ptrace的文档：
The ptrace() system call provides a means by which one process (the
       "tracer") may observe and control the execution of another process
       (the "tracee"), and examine and change the tracee's memory and
       registers. 
指出了ptrace是在两个进程之间进行监控操作，所以你提到的问题应该是在同一个进程上面操作才出现的问题。

**Comment by ele7enxxh** [comment]
感谢，另外是有评论的，不过是disqus，要翻墙才看得到。

**Comment by difcareer** [comment]
我有一些没有理解的，方便加QQ交流一下么，我的QQ是627443660

**Comment by rk700** [comment]
https://stackoverflow.com/questions/24157315/ptrace-one-thread-from-another
