### ISSUE TITLE
在头文件中识别一下c++

### ISSUE THREAD

**Issue by noword** [ele7enxxh/Android-Inline-Hook#11]
搞了我一晚上，以为是Android.mk的问题。结果是我的程序文件是CPP，最后去链接C的静态库，函数名识别不出。
在头文件里加上c++的判断就好了：
```
#ifdef 	__cplusplus
extern "C" {

...


}
```

**Comment by noword** [comment]
这个hook库非常好用，比那空有名气，臃肿又难用，时不时还出错，还要闭源的substrate，好多了。

**Comment by ele7enxxh** [comment]
感想认可

**Comment by noword** [comment]
老大，咋不更新呢？


`#ifndef _INLINEHOOK_H
#define _INLINEHOOK_H
#include <stdio.h>
#ifdef __cplusplus
extern "C" {
#endif

enum ele7en_status {
	ELE7EN_ERROR_UNKNOWN = -1,
	ELE7EN_OK = 0,
	ELE7EN_ERROR_NOT_INITIALIZED,
	ELE7EN_ERROR_NOT_EXECUTABLE,
	ELE7EN_ERROR_NOT_REGISTERED,
	ELE7EN_ERROR_NOT_HOOKED,
	ELE7EN_ERROR_ALREADY_REGISTERED,
	ELE7EN_ERROR_ALREADY_HOOKED,
	ELE7EN_ERROR_SO_NOT_FOUND,
	ELE7EN_ERROR_FUNCTION_NOT_FOUND
};

enum ele7en_status registerInlineHook(uint32_t target_addr, uint32_t new_addr, uint32_t **proto_addr);
enum ele7en_status inlineUnHook(uint32_t target_addr);
void inlineUnHookAll();
enum ele7en_status inlineHook(uint32_t target_addr);
void inlineHookAll();

#ifdef __cplusplus
}
#endif

#endif`
