### ISSUE TITLE
子线程触发hook时引起的父进程与子进程互锁问题

### ISSUE THREAD

**Issue by lykseek** [ele7enxxh/Android-Inline-Hook#22]
static int getAllTids(pid_t pid, pid_t *tids)
该函数返回线程组，除了自己。
但是，如果hook发生在子线程中，根据原来的传入参数getpid(),那么tids返回值依然是除了主线程之外的线程组。然后ptrace依然会使子线程锁住。然后，会造成子进程与主进程互锁。

建议，pid的传入参数为gettid(),然后，就不会发生问题了。
 if (tid != 0 && tid != gettid()) 这一行代码也需要修改为现在这个样子。

**Comment by ele7enxxh** [comment]
您好，可以提交pr吗，我来合并

**Comment by lykseek** [comment]
你好，已经提交

在 2018-10-25 16:20:10，"ele7enxxh" <notifications@github.com> 写道：


您好，可以提交pr吗，我来合并

**Comment by ele7enxxh** [comment]
已合并，感谢
