### ISSUE TITLE
ARM架构的动态库运行在Android X86设备上hook失败

### ISSUE THREAD

**Issue by WenhaiLin** [ele7enxxh/Android-Inline-Hook#7]
hook失败返回的错误：ELE7EN_ERROR_NOT_EXECUTABLE

APP只包含了ARM架构的动态库，hook的时候isExecutableAddr判断的结果是false

**Comment by ele7enxxh** [comment]
有测试代码吗

**Comment by WenhaiLin** [comment]
[DemoForBUG.zip](https://github.com/ele7enxxh/Android-Inline-Hook/files/641344/DemoForBUG.zip)


压缩包里X86_BUG_DEMO是hook的测试代码，编译成动态库后放到HookDemo中（已编译了一份在工程里面）。

编译动态库：
`ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=./Application.mk NDK_MODULE_PATH=.`

APP日志：
```
I/art: Late-enabling -Xcheck:jni
D/houdini: [24399] Initialize library(version: 5.0.7b_y.48396 RELEASE)... successfully.
V/Monotype: SetAppTypeFace- try to flip, app = com.example.hookdemo
V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
D/houdini: [24399] Added shared library /data/app/com.example.hookdemo-1/lib/arm/libX86HookDemo.so for ClassLoader by Native Bridge.
D/X86HookDemo: registerH dlo failed!
D/X86HookDemo: registerH AMO failed!
```

X86设备上加载arm动态库，是经过houdini处理

**Comment by kevinzxq** [comment]
X86上面好像是不能运行，大神解决了吗
